version: '3'

tasks:

  default:
    - task: install
    - task: webpack

  install:
    - npm install

  webpack:
    - npx webpack

  publish:clone:
    - git clone --depth=1 --single-branch --branch pages . .publish-pages

  publish:init:
    - git init .publish-pages
    - cd .publish-pages && git checkout --orphan pages
    - cd .publish-pages && git remote add origin ..

  publish:
    - cp -r stream.html dist .publish-pages
    - cd .publish-pages && git add *
    - cd .publish-pages && git commit -m "publish"
    - cd .publish-pages && git push origin pages

  publish:clean:
    - rm -rf .publish-pages

  serve:
    - python -m http.server --directory . 3000
